### ISSUE TITLE
Wrong Title

### ISSUE THREAD

**Issue by krisanalfa** [flipboxstudio/postman-test-generator#2]
As application deployed [here](http://postman.flipbox.co.id/). I see some mistakes:

1. The document title is wrong. It says:
> Laravel 5.3 - Form Validation

I assume it should be:

> Postman Test Generator

2. The heading is wrong. It says:
> JSON SCHEMA GENERATOR

I assume it should be:

> Postman Test Generator

**Comment by aqidd** [comment]
closed with this pull request #6
